---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: container-registry
      containers:
        - image: ${reg_ip}:8082/shuttle-docker-dev/tomcat:tomcat-${build_num}
          name: web
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  type: NodePort
  ports:
    - name: "web-port"
      port: 8080
      targetPort: 8080
      nodePort:30013
  selector:
    app: web
